# Generated by Django 4.2.1 on 2023-06-08 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="db_Image_Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_username_image", models.CharField(max_length=255)),
                ("db_id_image", models.CharField(max_length=255)),
                ("db_text_image", models.TextField(max_length=2000)),
                ("db_status_image", models.CharField(max_length=255)),
                ("db_type_image", models.CharField(max_length=255)),
                ("db_date_image", models.DateTimeField(auto_now=True)),
                (
                    "db_images",
                    models.ImageField(
                        blank=True, max_length=255, upload_to="PostImage/"
                    ),
                ),
                ("value_comment_image", models.CharField(max_length=255)),
                ("value_share_Image", models.CharField(max_length=255)),
                (
                    "db_comment_image",
                    models.ManyToManyField(
                        related_name="db_comment_image", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "db_like_image",
                    models.ManyToManyField(
                        related_name="db_like_image", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "db_share_image",
                    models.ManyToManyField(
                        related_name="db_share_image", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="db_Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char_email", models.CharField(max_length=255)),
                ("db_firstName", models.CharField(max_length=255)),
                ("db_lastName", models.CharField(max_length=255)),
                ("db_gender", models.CharField(max_length=125)),
                ("db_phoneNumber", models.CharField(max_length=255)),
                ("db_address", models.CharField(max_length=255)),
                ("db_date_DoB", models.DateField(blank=True)),
                ("db_last_login", models.DateTimeField(blank=True)),
                ("db_last_logout", models.DateTimeField(blank=True)),
                (
                    "db_photo",
                    models.ImageField(blank=True, max_length=255, upload_to="Profile/"),
                ),
                ("auth_token", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "db_email",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "db_friend_reciever",
                    models.ManyToManyField(
                        related_name="db_friend_reciever", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "db_friend_sender",
                    models.ManyToManyField(
                        related_name="db_friend_sender", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "db_sms_reciever",
                    models.ManyToManyField(
                        related_name="db_sms_reciever", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "db_sms_sender",
                    models.ManyToManyField(
                        related_name="db_sms_sender", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="db_Video_Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_username_video", models.CharField(max_length=255)),
                ("db_id_video", models.CharField(max_length=255)),
                ("db_text_video", models.TextField(max_length=2000)),
                ("db_status_video", models.CharField(max_length=255)),
                ("db_type_video", models.CharField(max_length=255)),
                (
                    "db_link_video",
                    models.ImageField(
                        blank=True, max_length=255, upload_to="PostVideo/"
                    ),
                ),
                ("db_date_video", models.DateTimeField(auto_now=True)),
                ("value_comment_video", models.CharField(max_length=255)),
                ("value_share_video", models.CharField(max_length=255)),
                (
                    "db_comment_video",
                    models.ManyToManyField(
                        related_name="db_comment_video", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "db_like_video",
                    models.ManyToManyField(
                        related_name="db_like_video", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "db_share_video",
                    models.ManyToManyField(
                        related_name="db_share_video", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="db_Write_Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_username_post", models.CharField(max_length=255)),
                ("db_id_post", models.CharField(max_length=255)),
                ("db_text_post", models.TextField(max_length=2000)),
                ("db_status_post", models.CharField(max_length=255)),
                ("db_type_post", models.CharField(max_length=255)),
                ("db_date_post", models.DateTimeField(auto_now=True)),
                ("value_comment_post", models.CharField(max_length=255)),
                ("value_share_post", models.CharField(max_length=255)),
                (
                    "db_comment_post",
                    models.ManyToManyField(
                        related_name="db_comment_post", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "db_like_post",
                    models.ManyToManyField(
                        related_name="db_like_post", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "db_share_post",
                    models.ManyToManyField(
                        related_name="db_share_post", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SMS_Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_sms_sender", models.CharField(max_length=255)),
                ("email_sms_reciever", models.CharField(max_length=255)),
                ("sms_text", models.TextField(max_length=50000)),
                ("value", models.CharField(max_length=255)),
                ("db_date_sms", models.DateTimeField(auto_now=True)),
                (
                    "sms_ForKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeChat.db_profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Share_Write",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id_share_Write", models.CharField(max_length=255)),
                ("email_share_Write_by", models.CharField(max_length=255)),
                ("email_share_Write_sender", models.CharField(max_length=255)),
                ("value_share_Write", models.CharField(max_length=255)),
                (
                    "Share_Write_ForKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeChat.db_write_post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Share_Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id_share_Video", models.CharField(max_length=255)),
                ("email_share_Video_by", models.CharField(max_length=255)),
                ("email_share_Video_sender", models.CharField(max_length=255)),
                ("value_share_Video", models.CharField(max_length=255)),
                (
                    "Share_Video_ForKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeChat.db_video_post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Share_Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id_share_Image", models.CharField(max_length=255)),
                ("email_share_Image_by", models.CharField(max_length=255)),
                ("email_share_Image_sender", models.CharField(max_length=255)),
                ("value_share_Image", models.CharField(max_length=255)),
                (
                    "Share_Image_ForKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeChat.db_image_post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like_Write",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id_Like_Write", models.CharField(max_length=255)),
                ("email_liked_Write_by", models.CharField(max_length=255)),
                ("email_liked_Write_sender", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "Like_Write_ForKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeChat.db_write_post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like_Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id_Like_Video", models.CharField(max_length=255)),
                ("email_liked_Video_by", models.CharField(max_length=255)),
                ("email_liked_Video_sender", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "Like_Video_ForKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeChat.db_video_post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like_Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id_Like_Image", models.CharField(max_length=255)),
                ("email_liked_Image_by", models.CharField(max_length=255)),
                ("email_liked_Image_sender", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "Like_Image_ForKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeChat.db_image_post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Friend_Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_friend_request_sender", models.CharField(max_length=255)),
                ("email_friend_request_reciever", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "Friend_ForKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeChat.db_profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment_Write",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id_comment_Write", models.CharField(max_length=255)),
                ("email_comment_Write_by", models.CharField(max_length=255)),
                ("email_comment_Write_sender", models.CharField(max_length=255)),
                ("comment_Text_Write", models.CharField(max_length=255)),
                ("value_comment_Write", models.CharField(max_length=255)),
                ("date_comment_Write", models.DateTimeField(auto_now=True)),
                (
                    "Comment_Write_ForKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeChat.db_write_post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment_Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id_comment_Video", models.CharField(max_length=255)),
                ("email_comment_Video_by", models.CharField(max_length=255)),
                ("email_comment_Video_sender", models.CharField(max_length=255)),
                ("value_comment_Video", models.CharField(max_length=255)),
                ("comment_Text_Video", models.CharField(max_length=255)),
                ("date_comment_Video", models.DateTimeField(auto_now=True)),
                (
                    "Comment_Video_ForKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeChat.db_video_post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment_Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id_comment_Image", models.CharField(max_length=255)),
                ("email_comment_Image_by", models.CharField(max_length=255)),
                ("email_comment_Image_sender", models.CharField(max_length=255)),
                ("value_comment_Image", models.CharField(max_length=255)),
                ("comment_Text_Image", models.CharField(max_length=255)),
                ("date_comment_Image", models.DateTimeField(auto_now=True)),
                (
                    "Comment_Image_ForKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeChat.db_image_post",
                    ),
                ),
            ],
        ),
    ]
